#!/bin/bash
#
# watcher	This shell script takes care of starting and stopping
#		watcher (file transfer daemon).
#
# chkconfig: - 58 74
# description: watcher is the recordings transfer daemon. \
# The Watcher is used to transfer the recordings made by the astersik PBX to the FTP server.

# Source function library.
. /etc/init.d/functions

prog=watcher
exec=/usr/sbin/$prog
conf=/etc/watcher/$prog.conf
log=/var/log/$prog
lockfile=/var/lock/subsys/$prog

start() {
	if [ ! -x $exec ]; then
		echo $exec not found or not executable
		exit 5
	fi
	if [ ! -f $conf ]; then
		echo $conf not found
		exit 6
	fi
	if [ ! -d $log ]; then
		mkdir $log
	fi
	if [ "$(pidof $prog)" ]; then
		echo $prog "is already running."
		exit 8
	fi
	echo -n $"Starting $prog: "
	daemon $prog $conf $log
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && touch $lockfile
	return $RETVAL
}

stop() {
	echo -n $"Shutting down $prog: "
	killproc $prog
	RETVAL=$?
	echo
	[ $RETVAL -eq 0 ] && rm -f $lockfile
	return $RETVAL
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  status)
	status $prog
	;;
  restart|force-reload)
	stop
	start
	;;
  try-restart|condrestart)
	if status $prog > /dev/null; then
		stop
		start
	fi
	;;
  reload)
	exit 3
	;;
  *)
	echo $"Usage: $0 {start|stop|status|restart|try-restart|force-reload}"
	exit 2
esac
